name: vote_smart
description: "A Vote Smart project"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  intl: ^0.20.2
  google_sign_in: '>=6.2.1'
  sign_in_with_apple: '>=6.1.2'
  firebase_auth: '>=5.3.3'
  cloud_firestore: '>=5.5.0'
  firebase_core: '>=2.21.1'
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  fl_chart: ^1.0.0
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5
  provider: ^6.1.2
  http: '>=1.0.0'
  uuid: '>=3.0.0'
  share_plus: ^7.2.2
  pdf: ^3.10.8
  logger: ^2.3.0
  graphview: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.9
  flutter_lints: ^5.0.0
  build_runner: ^2.4.9
  fake_cloud_firestore: ^3.1.0
  firebase_auth_mocks: ^0.14.1
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  
  assets:
    - assets/
